name: project_nomufinder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # â–¶ï¸ ê¸°ë³¸ Flutter ìœ í‹¸ë¦¬í‹°
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.0.3

  # ğŸŒ ë„¤íŠ¸ì›Œí¬ ë° ë°ì´í„° ì²˜ë¦¬
  http: ^1.3.0
  dio: ^5.4.0
  csv: ^5.0.0
  html: ^0.15.4
  http_parser: ^4.0.0
  flutter_dotenv: ^5.1.0

  # ğŸ”¥ Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.2
  firebase_database: ^10.4.2
  firebase_messaging: ^14.9.4

  # ğŸŒ ì§€ë„ ë° ìº˜ë¦°ë”
  google_maps_flutter: ^2.3.0
  table_calendar: ^3.0.9
  add_2_calendar: ^3.0.1

  # ğŸ–¼ï¸ ì´ë¯¸ì§€ ë° íŒŒì¼ ê´€ë ¨
  file_selector: ^0.9.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # ğŸ“¦ ë¼ìš°íŒ… / ìƒíƒœê´€ë¦¬
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.0

  # ğŸ”— ê¸°íƒ€ ê¸°ëŠ¥
  url_launcher: ^6.2.5
  html_unescape: ^2.0.0 # ìœ íŠœë¸Œ ê´€ë ¨ ë””ì½”ë”©
  google_sign_in: ^6.1.4 # Google ë¡œê·¸ì¸
#  flutter_local_notifications: 16.3.2 # ì´ì „ ì•ˆì • ë²„ì „


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:  # ì•„ì´ì½˜ ì„¤ì • ì¶”ê°€ë¨
  android: true
  ios: true
  image_path: "assets/images/logo2.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
    - assets/images/korea_map.png
    - assets/lawyers_by_region_ver2.json
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png
    - assets/images/banner4.png
    - assets/images/default_user.png
    - assets/images/google_logo.png
    - assets/images/logo3.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Anybody
      fonts:
        - asset: assets/fonts/Anybody-Regular.ttf
        - asset: assets/fonts/Anybody-Bold.ttf
          weight: 700